if (!require(shiny)) install.packages("shiny")
library(shiny)
if (!require(shinythemes)) install.packages("shinythemes")
library(shinythemes)
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
if (!require(RColorBrewer)) install.packages("RColorBrewer")
library(RColorBrewer)
if (!require(viridisLite)) install.packages("viridisLite")
library(viridisLite)
if (!require(reticulate)) install.packages("reticulate")
library(reticulate)
