---
title: "Sandbox"
author: "Eren Akgunduz"
date: "19 April 2023"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The data

```{r, message=FALSE}
library(tidyverse)
```

### For starters

```{r}
df <- read.csv("data/all.csv", stringsAsFactors = FALSE)
df$Damage <- gsub(".*\\((\\d+)\\).*", "\\1", df$Damage)
df$Damage <- gsub("(\\d+)\\s*\\((\\d+)\\)", "pmax(\\1, \\2)", df$Damage)
df$Damage <- gsub("(\\d+)\\*(\\d+)", "\\1+\\2", df$Damage)
df$Damage <- gsub("(\\d+)x(\\d+)", "\\1*\\2", df$Damage)
df$Damage <- sapply(df$Damage, function(x) eval(parse(text = x)))
df$Damage <- as.numeric(df$Damage)
df$Stun <- gsub(".*\\((\\d+)\\).*", "\\1", df$Stun)
df$Stun <- gsub("(\\d+)\\s*\\((\\d+)\\)", "pmax(\\1, \\2)", df$Stun)
df$Stun <- gsub("(\\d+)\\*(\\d+)", "\\1+\\2", df$Stun)
df$Stun <- gsub("(\\d+)x(\\d+)", "\\1*\\2", df$Stun)
df$Stun <- sapply(df$Stun, function(x) eval(parse(text = x)))
df$Stun <- as.numeric(df$Stun)
df$health <- as.numeric(df$health)
df$stun <- as.numeric(df$stun)
df$vgauge1 <- as.numeric(df$vgauge1)
df$vgauge2 <- as.numeric(df$vgauge2)
df$fDash <- as.numeric(df$fDash)
df$bDash <- as.numeric(df$bDash)
df$fWalk <- as.numeric(df$fWalk)
df$bWalk <- as.numeric(df$bWalk)
df$throwHurt <- as.numeric(df$throwHurt)
df$throwRange <- as.numeric(df$throwRange)
na_rows <- df[!complete.cases(df), ]
na_rows
# df$Damage %>%
#   tibble() %>%
#   print(n = Inf)
# df$Stun %>%
#   tibble() %>%
#   print(n = Inf)
write.csv(df, "data/all.csv", row.names = FALSE)
```

### KDE

<!-- # ```{r}
# ggplot(data, aes(onBlock)) +
#   geom_density()
# ``` -->
